apps/mysite/urls.py
from django.urls import path
from .views import IndexListView
app_name = "mysite"

urlpatterns = [
    #путь для загрузки главной страницы
    path("", IndexListView.as_view(), name="index"),
]

apps/users/urls.py
from django.urls import path
from .views import UserRegistrationView, CabinetView

app_name = "users"

urlpatterns = [
    path('accounts/register/', UserRegistrationView.as_view(), name='register'),
    path('accounts/cabinet/', CabinetView.as_view(), name='profile'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('apps.mysite.urls')),
    path('', include('apps.users.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/mysite/models.py
from django.db import models
from apps.users.models import User

class Band(models.Model):
    name = models.CharField(max_length=100)
    foundation_year = models.PositiveSmallIntegerField()
    foundation_city = models.CharField(
        max_length=100, blank=True, null=True
        )
    
    def __str__(self):
        return self.name 

class Album(models.Model):
    name = models.CharField(max_length=255)
    release_year = models.PositiveSmallIntegerField()
    band = models.ForeignKey(Band, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name}-{self.band}-{self.release_year}"

    @staticmethod
    def get_old_albums():
        return Album.objects.filter(release_year__lte=2000)


class Track(models.Model):
    name = models.CharField(max_length=100)
    album = models.ForeignKey(
        Album, on_delete=models.SET_NULL, null=True, blank=True,
        related_name='tracks', 
    )
    is_single = models.BooleanField(default=False)
    band = models.ForeignKey(
        Band, on_delete=models.CASCADE,
        related_name='tracks'
    )

    def __str__(self):
        return f'{self.name}-{self.band}'


class InstagramPost(models.Model):
    name = models.CharField(max_length=255)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='instagramposts')

    def __str__(self):
        return self.name
    



class Author(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)

    def __str__(self):
        return self.first_name + self.last_name
    

class Book(models.Model):
    name = models.CharField(max_length=100)
    authors = models.ManyToManyField(Author) 

    def __str__(self):
        return self.name
    

apps/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    name = models.CharField(
        verbose_name="Name of User", blank=True, max_length=255
        )

    def __str__(self):
        return self.username

    

apps/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()

class UserCreationModelForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'username', 'name', 'email', 'password1', 'password2'
            ]
            

apps/mysite/views.py
from django.shortcuts import render
from django.views.generic import ListView

class IndexListView(ListView):
    template_name = "main_page/index.html"

    def get_queryset(self, *args, **kwargs):
        return "not objects"

    

apps/users/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.contrib.auth import get_user_model
from django.views.generic import CreateView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import UserCreationModelForm

User = get_user_model()

class UserRegistrationView(CreateView):
    form_class = UserCreationModelForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'


class CabinetView(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'main_page/user_cabinet.html'

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

templates/bases/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'mysite:index' %}">Лого</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'mysite:index' %}"> Главная <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">О нас</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Разделы
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                {% if user.is_authenticated %}
                <a class="dropdown-item" href="{% url 'users:profile' %}">Перейти в профиль</a>
                <a class="dropdown-item" href="{% url 'logout' %}">Выйти</a>
                <a class="dropdown-item" href="{% url 'password_reset' %}">Поменять пароль</a>

                {% else %}
                <a class="dropdown-item" href="{% url 'users:register' %}">Регистрация</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'login' %}">Войти</a>
                {% endif %}
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>


      {% block content %}
        Нет информации
      {% endblock %}

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

templates/main_page/index.html
{% extends 'bases/_base.html' %}


{% block content %}
    <h1> Main Page </h1>
{% endblock %}

templates/main_page/user_cabinet.html
{% extends 'bases/_base.html' %}

{% block content %}
    <h1>{{user.username}}</h1>
    <strong><p>{{user.email}}</p></strong>
{% endblock %}